replicaCount: 1

image:
  repository: ""   # 🔧 Replace with your frontend image repo
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: LoadBalancer
  port: 80

serviceAccount:
  create: false

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"  # ✅ If you want HTTPS only
  hosts:
    - host: app.sanketsarode.shop
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: frontend-tls
      hosts:
        - app.sanketsarode.shop

autoscaling:
  enabled: false
