replicaCount: 1

image:
  repository: ""   # Set your backend image repository (e.g., <your-ecr-repo>)
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP     # ✅ Using ClusterIP for internal service
  port: 3000

serviceAccount:
  create: false

ingress:
  enabled: true
  className: "nginx"   # or leave null if default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
   
  hosts:
    - host: backend.sanketsarode.shop
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: backend-tls
      hosts:
        - backend.sanketsarode.shop

autoscaling:
  enabled: false
