replicaCount: 1

image:
  repository: ""   # Set your backend image repository (e.g., <your-ecr-repo>)
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP     # ✅ Using ClusterIP for internal service
  port: 3000

serviceAccount:
  create: false

ingress:
  enabled: false    # ❌ Disabling Helm-managed Ingress; using shared ALB instead

# Leave TLS config out since Ingress is not being created by Helm
# It will be handled in the shared ALB Ingress YAML

autoscaling:
  enabled: false
